title: Titulillo
author: Juanjo00
email: someone@something.com
description: > # this means to ignore newlines until "baseurl:"
  Hey this is some descriptive description that describes what is being described by a description that is very descriptive in it's own nature.
  By being descriptive, the description is considered a descriptor which describes the descriptee. 
  A descriptee is the thing/person/place being described in a descriptive way.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
